esphome:
  name: sco2_ota
  platform: ESP8266
  board: d1_mini
  on_boot:
    - light.turn_on:
        id: color_leds_id
        transition_length: 0s
        red: 0.0
        green: 0.0
        blue: 0.5
        
wifi:
  ssid: "WeidInternet - IOT"
  password: !secret wifi_password_iot
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sco2 Ota Fallback Hotspot"
    password: "kBkqXcFE8FKH"

globals:
  - id: red
    type: float
#  - id: green
#    type: float
     
captive_portal:

# Example configuration entry
debug:

# Logger must be at least debug (default)
logger:
  level: debug

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret esphome_ha_api

ota:
  password: !secret esphome_ha_api

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  frequency: 100kHz

sensor:
  - platform: scd30
    i2c_id: bus_a
    address: 0x61
    co2:
      name: "scd30 CO2"
      id: scd30_co2
      accuracy_decimals: 1
      on_value:
        then:
        - if:
            condition:
              and:
                - lambda: return x > 300.0;
                - lambda: return x < 1000.0;
            then:
              - light.control:
                  id: color_leds_id
                  green: 0.75
                  red: 0.0
                  blue: 0.0
                  transition_length: 2.0s
                  brightness: 70%
        - if:
            condition:
              and:
                - lambda: return x > 1000.0;
                - lambda: return x < 1500.0;
            then:
              - light.control:
                  id: color_leds_id
                  red: !lambda "return x / 500.0 - 2.0;"
                  green: !lambda "return (1 - ((x - 1000) / 500));"
                  blue: 0.0
                  transition_length: 2.0s
                  brightness: 70%
        - if:
            condition:
              and:
                - lambda: return x > 1500.0;
                - lambda: return x < 10000.0;
            then:
              - light.control:
                  id: color_leds_id
                  green: 0.0
                  red: 0.75
                  blue: 0.0
                  transition_length: 2.0s
                  brightness: 70%
    temperature:
      name: "scd30 Temperature"
      id: scd30_temperature
      accuracy_decimals: 1
    humidity:
      name: "scd30 Humidity"
      id: scd30_humidity
      accuracy_decimals: 1
    temperature_offset: 5.5
    update_interval: 10s

light:
  - platform: neopixelbus
    id: color_leds_id
    type: GRB
    method: ESP8266_ASYNC_UART1
    pin: D4
    num_leds: 7
    name: "LED Light"
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
